// ESLint flat config (ESLint v9+). The Nuxt-aware rules are generated by the
// @nuxt/eslint module into .nuxt/eslint.config.mjs during `nuxt prepare`.
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    // Wallet adapters and third-party XRPL SDK surfaces are loosely typed in
    // this starter. Keep `any` visible as a warning instead of failing lint —
    // tighten these types as you build out your own app.
    '@typescript-eslint/no-explicit-any': 'warn',
    // Single-word component names (Header, etc.) are intentional in the
    // template and map to dynamically generated pages.
    'vue/multi-word-component-names': 'off',
  },
})
