// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/6/2026, 5:20:23 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/plugins/**/*.{js,ts,mjs}","/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/composables/**/*.{js,ts,mjs}","/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/utils/**/*.{js,ts,mjs}","/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/app.config.{js,ts,mjs}","/Users/thomashussenet/Documents/commons/code/scaffold-xrp/apps/web-nuxt/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;